# Generated by Django 5.2.7 on 2025-11-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create'), ('can_view', 'Can view'), ('can_delete', 'Can delete'), ('can_edit', 'Can edit')]},
        ),
    ]
