# Generated by Django 5.2.7 on 2025-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['grade', 'first_name'],
            },
        ),
    ]
